replicaCount: 1

image:
  repository: ghcr.io/sergeychernyshov-code/s3-file-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls: []

env: []

resources: {}

affinity: {}
