replicaCount: 1

image:
  repository: ghcr.io/sergeychernyshov-code/s3-file-server
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  - name: S3_BUCKET
    value: "my-bucket"
  - name: MINIO_ENDPOINT
    value: "s3-file-server-minio.default.svc.cluster.local:9000"
  - name: MINIO_ACCESS_KEY
    value: "minioadmin"
  - name: MINIO_SECRET_KEY
    value: "minioadmin"

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
