apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-file-server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "s3-file-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "s3-file-server.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: S3_BUCKET
              value: "my-bucket"
            - name: MINIO_ENDPOINT
              value: "my-minio-minio.default.svc.cluster.local:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"