apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-file-server.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "s3-file-server.name" . }}