name: CI/CD Workflow 

on:
  push:
    branches: [main]

permissions:
  contents: write 
  packages: write

jobs:
  CI-CD:
    runs-on: ubuntu-24.04 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Init Go module
      run: |
        cd src
        go mod init github.com/sergeychernyshov-code/s3www-minio 
        go mod tidy
        
    - name: Build Go binary
      run: make -C src build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: make -C src docker-push
      env:
        GITHUB_USER: ${{ github.repository_owner }}

    - name: A job to install MicroK8s
      uses: balchua/microk8s-actions@v0.4.3
      with:
        channel: '1.26/stable'
        addons: '["dns", "ingress", "rbac", "hostpath-storage", "registry"]'
    
    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: |
        terraform plan \
          -var="s3_bucket=${{ secrets.S3_BUCKET }}" \
          -var="minio_endpoint=${{ secrets.MINIO_ENDPOINT }}" \
          -var="minio_access_key=${{ secrets.MINIO_ACCESS_KEY }}" \
          -var="minio_secret_key=${{ secrets.MINIO_SECRET_KEY }}"

    - name: Terraform Apply
      working-directory: terraform
      run: |
        terraform apply -auto-approve \
          -var="s3_bucket=${{ secrets.S3_BUCKET }}" \
          -var="minio_endpoint=${{ secrets.MINIO_ENDPOINT }}" \
          -var="minio_access_key=${{ secrets.MINIO_ACCESS_KEY }}" \
          -var="minio_secret_key=${{ secrets.MINIO_SECRET_KEY }}"

    - name: Start ngrok tunnel (HTTP on port 80)
      env:
        NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      run: |
        ngrok config add-authtoken $NGROK_AUTHTOKEN
        nohup ngrok http 80 > ngrok.log &
        sleep 10
        curl http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Output curl command and URL and sleep for 10 minutes, leaving application serving the file
      run: |
        echo curl -v -o giphy.gif "$( curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' )/giphy.gif" && sleep 600
